trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
# Install .NET 9 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore dependencies
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Build project
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Publish project
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

# Deploy to Azure App Service (Free)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureFreeAppService'  # Update this to your actual service connection name
    appName: 'FirstAzureDemo'                 # Update this to your actual Azure App Service name
    appType: 'webApp'                         # <-- Required property
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
